service: shopify-app-tags
app: shopify-app-tags
org: pixelter

plugins:
  - serverless-offline

custom:
  shopifyConfig: ${file(./config/shopify.${self:provider.stage}.json)
  databaseConfig: ${file(./config/database.${self:provider.stage}.json)}
  hostConfig: ${file(./config/host.${self:provider.stage}.json)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    # Shopify App
    SHOPIFY_APP_KEY: ${self:custom.shopifyConfig.apiKey}
    SHOPIFY_APP_SECRET: ${self:custom.shopifyConfig.apiSecret}
    SHOPIFY_APP_ID: ${self:custom.shopifyConfig.id}
    SHOPIFY_SCOPES: ${self:custom.shopifyConfig.scopes}
    # Database
    DB_URL: ${self:custom.databaseConfig.url}
    # Host
    APP_HOST: ${self:custom.hostConfig.url}

functions:
  # Shopify Installl
  install:
    handler: src/shopify/install.handle
    events:
      - http:
          path: install
          method: get
  installCallback:
    handler: src/shopify/callback.handle
    events:
      - http:
          path: install/callback
          method: get
  # Crons
  shopifyCronRegural:
    handler: src/shopify/cron.regural
    timeout: 600
    events:
      - schedule: rate(4 hours)
  shopifyCronScheduled:
    handler: src/shopify/cron.scheduled
    timeout: 250
    events:
      - schedule: rate(5 minutes)
  # API Handler
  api:
    handler: src/api/handler.handle
    events:
      - http:
          path: api/{action}
          method: post
          cors: true
          request:
            parameters:
              paths:
                action: true
